// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mythpanxvzvspeynphay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dGhwYW54dnp2c3BleW5waGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MzcxNDgsImV4cCI6MjA2ODIxMzE0OH0.DxPrl7zbl5BfADaw1fXj0_b1ZiVzIMe2b23i4PPpg0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});